- name: Workflow output'tan cihazları al ve ServiceCore'a gönder
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Fetch Devices çıktısından cihaz isimlerini ve ip adreslerini al
      set_fact:
        device_name_ip_list: "{{ hostvars['localhost']['shared_device_name_ip_list'] }}"

    - name: Her cihazı ServiceCore'a gönder
      uri:
        url: "{{ servicecore_api_url }}"
        method: POST
        headers:
          ApiKey: "{{ servicecore_api_key }}"
          Content-Type: "application/json"
        body_format: json
        body:
          assetStatusId: "{{ asset_status_id }}"
          name: "{{ item.name }}"
          description: "IP Address: {{ item.ip }}"
          assetTypeId: "{{ asset_type_id }}"
        status_code: 200
      loop: "{{ device_name_ip_list }}"
      loop_control:
        label: "{{ item.name }} | {{ item.ip }}"
