- name: Dış API'den cihazları çek ve paylaş
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Authorization token oluştur
      set_fact:
        d42_auth_header: "Basic {{ (d42_username + ':' + d42_password) | b64encode }}"

    - name: Cihaz listesini dış API'den çek
      uri:
        url: "https://{{ d42_host }}:{{ d42_port }}/api/1.0/devices/all"
        method: GET
        headers:
          Authorization: "{{ d42_auth_header }}"
        return_content: yes
        validate_certs: no
      register: devices_response

    - name: Cihaz isimlerini ve IP adreslerini ayıkla
      set_fact:
        device_name_ip_list: >-
          {{ devices_response.json.Devices | map('extract', ['name', 'ip_addresses']) | map('combine', [{'name': item.0, 'ip': (item.1[0] if item.1|length > 0 else '')}]) | list }}

    - name: Workflow output olarak cihaz isimlerini ve ip adreslerini paylaş
      set_stats:
        data:
          shared_device_name_ip_list: "{{ device_name_ip_list }}"